# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  codelab:
    working_directory: ~/codelab
    machine: true
    branches:
      ignore: gh-pages
    steps:
      - checkout
      - run: cd codelab && make build-ci
      - gh-pages/deploy:
        ssh-fingerprints: 'c1:d1:20:94:20:67:f4:88:75:e2:c6:8d:cf:07:3b:ae'
orbs:
  gh-pages: sugarshin/gh-pages@0.0.6
workflows:
  build:
    jobs:
      - codelab