# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  codelab:
    working_directory: ~/labs
    docker:
      - image: circleci/golang:1.11.6-node
    steps:
      - checkout
      - run: CGO_ENABLED=0 go get github.com/googlecodelabs/tools/claat
      - run: cd codelab && claat export codelab.md
      - run: cd become-svelte && npm install
      - run: cd become-svelte && npm build
      - run: npm install -g firebase-tools
      - run: firebase deploy --token $FIREBASE_TOKEN

workflows:
  build:
    jobs:
      - codelab