name: Build and Deploy codelab

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: |
        cd codelab
        make build-ci

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: codelab/build # The folder the action should deploy.